### ISSUE TITLE
Facebook login not working

### ISSUE THREAD

**Issue by malcolm-bklyn** [SaifurRahmanMohsin/Social-Plugin#4]
Hi,

I'm having a problem with Facebook loginnot working properly. This is the response from Facebook:

```
Errors during multi transfer (Guzzle\Http\Exception\ClientErrorResponseException) ./vendor/guzzle/guzzle/src/Guzzle/Http/Exception/BadResponseException.php line 43 
Client error response 
[status code] 400 
[reason phrase] Bad Request 
[url] https://graph.facebook.com/v2.2/me?fields=id%2Cname%2Cfirst_name%2Clast_name%2Cemail%2Chometown%2Cbio%2Cpicture.type%28large%29%2Cgender%2Clocale%2Clink&
```

Is there a fix for this?

**Comment by SaifurRahmanMohsin** [comment]
Thanks for reporting this. I’ll look into it and get back to you in a couple of hours with a fix.

**Comment by malcolm-bklyn** [comment]
Thanks!



______

Malcolm Paul

malcolm@bklyn.co

1-347-241-2690

[image: bklyn_letter_sign]



*From:* Saifur Rahman Mohsin [mailto:notifications@github.com]
*Sent:* Friday, November 18, 2016 2:13 PM
*To:* SaifurRahmanMohsin/Social-Plugin <Social-Plugin@noreply.github.com>
*Cc:* malcolm-bklyn <malcolm@bklyn.co>; Author <author@noreply.github.com>
*Subject:* Re: [SaifurRahmanMohsin/Social-Plugin] Facebook login not
working (#4)



Thanks for reporting this. I’ll look into it and get back to you in a
couple of hours with a fix.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/SaifurRahmanMohsin/Social-Plugin/issues/4#issuecomment-261616052>,
or mute the thread

**Comment by SaifurRahmanMohsin** [comment]
Facebook has updated their API and even the packages the plugin depended on had made some changes which led to this issue. I have made a fix and pushed the update. Kindly read the instructions in the upgrade guide of the plugin before upgrading and you should be able to solve the issue. If it isn’t too much trouble could you let me know if it has solved your issue here? And also, if you liked my plugin kindly drop a good review and rating. Thanks in advance.

**Comment by malcolm-bklyn** [comment]
HI SaifurRahmanMoshin,

Just updated the plugin now I have this error:

```
The component 'Mohsin\Social\Components\Facebook' does not contain a method 'param'.

/var/www/vhosts/thinklabserver.com/nyco.thinklabserver.com/malcolm/api/modules/cms/classes/ComponentBase.php line 278

```

|   #   |   Called Code 	|   Document 	|   Line  |
|   ----   |   ----   |   ---- | ---- |
|   54 	|   Cms\Classes\ComponentBase->__call(…) 	| ~/plugins/rainlab/user/components/Account.php 	|   62   |
|   53 	|   RainLab\User\Components\Account->onRun() 	| ~/plugins/mohsin/social/components/BaseProviderComponent.php 	|   67   |
|   52 	|   Mohsin\Social\Components\BaseProviderComponent->onRun() 	| ~/plugins/mohsin/social/components/Facebook.php 	|   32   |
|   51 	|   Mohsin\Social\Components\Facebook->onRun() 	|   | |

**Comment by SaifurRahmanMohsin** [comment]
Kindly do this: go into the plugins/mohsin/social folder and delete the vendor folder and composer.lock file completely. If you login to your backend via SSH then these are the commands:

```
cd public_html/plugins/mohsin/social/
rm composer.lock
rm -rf vendor/
```
Otherwise if you use FTP or web-based file manager, the deletion should be very straight-forward.
Now from the backend, kindly perform a force update. Now check the plugin and it should work well. I don’t remember ever adding a param function so I think there may have been an issue with your update. A force update should solve it.
